--use movies;

--SELECT NAME
--FROM MOVIESTAR
--WHERE GENDER = 'W' AND name IN ( SELECT name FROM MOVIEEXEC WHERE NETWORTH > 1000000);

--SELECT NAME
--FROM MOVIESTAR
--WHERE NAME NOT IN (SELECT name FROM MOVIEEXEC);

--SELECT TITLE
--FROM MOVIE
--WHERE LENGTH > ALL(SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars');

--SELECT TITLE, NAME
--FROM MOVIE INNER JOIN MOVIEEXEC
--ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
--WHERE MOVIEEXEC.NETWORTH > ALL(SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin');

