--USE SHIPS;

--SELECT DISTINCT COUNTRY
--FROM CLASSES
--WHERE NUMGUNS = (SELECT TOP 1 NUMGUNS FROM CLASSES ORDER BY NUMGUNS DESC);

--SELECT DISTINCT CLASS
--FROM SHIPS
--WHERE NAME IN (SELECT SHIP FROM OUTCOMES WHERE RESULT = 'SUNK');

--SELECT DISTINCT C.CLASS, S.NAME
--FROM CLASSES AS C INNER JOIN SHIPS AS S
--ON C.CLASS = S.CLASS
--WHERE C.BORE = 16;

--SELECT NAME
--FROM BATTLES
--WHERE NAME IN (SELECT BATTLE FROM OUTCOMES WHERE SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS = 'KONGO'));

SELECT CLASS, NAME
FROM SHIPS
WHERE CLASS IN (SELECT CLASS FROM CLASSES AS C WHERE C.NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES AS C2 WHERE C.BORE = C2.BORE));