USE PC;

--SELECT MAKER
--FROM PRODUCT
--WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED > 500);

--SELECT CODE, MODEL, PRICE
--FROM PRINTER
--WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER);

--SELECT *
--FROM LAPTOP
--WHERE SPEED < ALL(SELECT SPEED FROM PC);

--SELECT TOP 1 MODEL, PRICE
--FROM ((SELECT MODEL, PRICE FROM PC) UNION 
--	(SELECT MODEL, PRICE FROM LAPTOP) UNION 
--	(SELECT MODEL, PRICE FROM PRINTER)) AS P
--ORDER BY PRICE DESC;

--SELECT MAKER
--FROM PRODUCT INNER JOIN PRINTER
--ON PRODUCT.MODEL = PRINTER.MODEL
--WHERE PRINTER.PRICE < (SELECT PRICE FROM PRINTER WHERE COLOR = 'Y');

--SELECT P.MAKER
--FROM PRODUCT P INNER JOIN PRINTER PR 
--ON P.MODEL = PR.MODEL
--WHERE PR.COLOR = 'Y' AND PR.PRICE = (SELECT TOP 1 PRICE 
--					FROM PRINTER 
--					WHERE COLOR = 'Y' 
--					ORDER BY PRICE ASC);

--SELECT DISTINCT MAKER
--FROM PRODUCT
--WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED = (SELECT TOP 1 SPEED FROM PC 
--	WHERE RAM = (SELECT TOP 1 RAM FROM PC ORDER BY RAM ASC) ORDER BY SPEED DESC));