--CREATE DATABASE TEST2;
USE TEST2;

--CREATE TABLE PRODUCT
--(
--	ID INT IDENTITY,
--	MODEL CHAR(4),
--	MAKER CHAR(1),
--	TYPE VARCHAR(7)
--);

--CREATE TABLE PRINTER
--(
--	ID INT IDENTITY,
--	CODE INT,
--	MODEL CHAR(4),
--	PRICE DECIMAL(5,2)
--);

--INSERT INTO PRINTER
--VALUES (200, 'M', 345.89);

--ALTER TABLE PRINTER
--ADD TYPE VARCHAR(6), COLOR CHAR(1);

--ALTER TABLE PRINTER
--DROP COLUMN PRICE;

--DROP TABLE PRODUCT;
--DROP TABLE PRINTER;
